# Generated by scripts/formula.sh in daniel-oh/background-remover for v0.2.1.
class BackgroundRemover < Formula
  desc "Background removal as a small HTTP service"
  homepage "https://github.com/daniel-oh/background-remover"
  version "0.2.1"
  license any_of: ["MIT", "Apache-2.0"]

  on_macos do
    on_arm do
      url "https://github.com/daniel-oh/background-remover/releases/download/v0.2.1/background-remover-v0.2.1-aarch64-apple-darwin.tar.gz"
      sha256 "b45f19baf7bf59dbc28d2707cefe8c694b035e8db35ed485871ebc24d769e9b7"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/daniel-oh/background-remover/releases/download/v0.2.1/background-remover-v0.2.1-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "3f22ef7e83180ab84bc4931a2543cb761aab3e04b5ffd3a6a4af6376ca80308f"
    end
    on_intel do
      url "https://github.com/daniel-oh/background-remover/releases/download/v0.2.1/background-remover-v0.2.1-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "a9220f0c3254b1e1555b82461b3d19ae8f0874f1293953ec13eb62c053729014"
    end
  end

  def install
    bin.install "background-remover"
  end

  def caveats
    <<~EOS
      The model (178 MB) is not bundled. Fetch it once:
        mkdir -p #{var}/background-remover
        curl -L -o #{var}/background-remover/isnet-general-use.onnx \\
          https://github.com/danielgatis/rembg/releases/download/v0.0.0/isnet-general-use.onnx
      Then either run it in the foreground:
        MODEL_PATH=#{var}/background-remover/isnet-general-use.onnx background-remover
      or as a service on 127.0.0.1:7000, which uses that path:
        brew services start background-remover
    EOS
  end

  service do
    run [opt_bin/"background-remover"]
    environment_variables MODEL_PATH: var/"background-remover/isnet-general-use.onnx",
                          BIND:       "127.0.0.1"
    keep_alive true
    log_path var/"log/background-remover.log"
    error_log_path var/"log/background-remover.log"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/background-remover --version")
  end
end
