# Generated by scripts/formula.sh in daniel-oh/background-remover for v0.3.0.
class BackgroundRemover < Formula
  desc "Background removal as a small HTTP service"
  homepage "https://github.com/daniel-oh/background-remover"
  license any_of: ["MIT", "Apache-2.0"]

  on_macos do
    on_arm do
      url "https://github.com/daniel-oh/background-remover/releases/download/v0.3.0/background-remover-v0.3.0-aarch64-apple-darwin.tar.gz"
      sha256 "8eb8cebd96c6a4ab0e2e0c0fefaf7867a7b74d409927ecb1d2c8777a2bd27e27"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/daniel-oh/background-remover/releases/download/v0.3.0/background-remover-v0.3.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "73461f963909b1bbe1f61c9f083a27c2010984af35b7b5428a55e0134ab24da3"
    end
    on_intel do
      url "https://github.com/daniel-oh/background-remover/releases/download/v0.3.0/background-remover-v0.3.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "e2ae05913f4bc2545febcf574053a2141de8fcfdc3b5d3eda855db5ec951653d"
    end
  end

  def install
    bin.install "background-remover"
  end

  def caveats
    <<~EOS
      Cut out a photo:
        background-remover photo.jpg          # writes photo-cutout.png
      The first run fetches the model (178 MB, once) into your cache
      directory and verifies it;  does the
      same on its own. To run the HTTP service on 127.0.0.1:7000 instead:
        background-remover --fetch-model && brew services start background-remover
    EOS
  end

  service do
    run [opt_bin/"background-remover"]
    environment_variables BIND: "127.0.0.1"
    keep_alive true
    log_path var/"log/background-remover.log"
    error_log_path var/"log/background-remover.log"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/background-remover --version")
  end
end
