# Generated by scripts/formula.sh in daniel-oh/background-remover for v0.3.1.
class BackgroundRemover < Formula
  desc "Background removal as a small HTTP service"
  homepage "https://github.com/daniel-oh/background-remover"
  license any_of: ["MIT", "Apache-2.0"]

  on_macos do
    on_arm do
      url "https://github.com/daniel-oh/background-remover/releases/download/v0.3.1/background-remover-v0.3.1-aarch64-apple-darwin.tar.gz"
      sha256 "9faff4f1fa566679682bac000b015fa16a4c397890b3d32248a540461ff27c61"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/daniel-oh/background-remover/releases/download/v0.3.1/background-remover-v0.3.1-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "bd3b65abd99541bf8e8f77b78cc46de45debfbf73e8c6a1da1b363541f00cbe9"
    end
    on_intel do
      url "https://github.com/daniel-oh/background-remover/releases/download/v0.3.1/background-remover-v0.3.1-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "75cb973a34bc43be6dd9397c2f26f3d3a2e5936c70f18341ec61e85b6f4ff2c3"
    end
  end

  def install
    bin.install "background-remover"
  end

  def caveats
    <<~EOS
      Cut out a photo:
        background-remover photo.jpg          # writes photo-cutout.png
      The first run fetches the model (178 MB, once) into your cache
      directory and verifies it; `background-remover --fetch-model` does the
      same on its own. To run the HTTP service on 127.0.0.1:7000 instead:
        background-remover --fetch-model && brew services start background-remover
    EOS
  end

  service do
    run [opt_bin/"background-remover"]
    environment_variables BIND: "127.0.0.1"
    keep_alive true
    log_path var/"log/background-remover.log"
    error_log_path var/"log/background-remover.log"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/background-remover --version")
  end
end
